/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bai1.CaesarORCL;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author vogiadat
 */
public class CaesarORCL extends javax.swing.JFrame {

	/**
	 * Creates new form CaesarORCL
	 */
	private Connection conn = DB.getConnect();

	public CaesarORCL() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                txtMessage = new javax.swing.JTextArea();
                jLabel3 = new javax.swing.JLabel();
                spnKey = new javax.swing.JSpinner();
                ckFunction = new javax.swing.JCheckBox();
                lblSelect = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                btnEcrypt = new javax.swing.JButton();
                btnDecrypt = new javax.swing.JButton();
                txtEcryptMessage = new javax.swing.JTextArea();
                txtDeryptMessage = new javax.swing.JTextArea();
                jLabel5 = new javax.swing.JLabel();
                logout = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel1.setText("Caesar Cipher With Oracle");

                jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                jLabel2.setText("Message:");

                txtMessage.setColumns(20);
                txtMessage.setRows(5);

                jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                jLabel3.setText("Key:");

                ckFunction.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
                ckFunction.setText("Use Function");
                ckFunction.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                ckFunctionActionPerformed(evt);
                        }
                });

                lblSelect.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
                lblSelect.setText("( Default use procedure method)");

                jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                jLabel4.setText("Encrypt message:");

                btnEcrypt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                btnEcrypt.setText("Ecrypt");
                btnEcrypt.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnEcryptActionPerformed(evt);
                        }
                });

                btnDecrypt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                btnDecrypt.setText("Decrypt");
                btnDecrypt.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnDecryptActionPerformed(evt);
                        }
                });

                txtEcryptMessage.setEditable(false);
                txtEcryptMessage.setColumns(20);
                txtEcryptMessage.setRows(5);

                txtDeryptMessage.setEditable(false);
                txtDeryptMessage.setColumns(20);
                txtDeryptMessage.setRows(5);

                jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                jLabel5.setText("Decrypt message:");

                logout.setText("Logout");
                logout.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                logoutActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2)
                                                        .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel3)
                                                        .addComponent(spnKey, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(jLabel4)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(txtEcryptMessage)
                                                                        .addGap(29, 29, 29)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(btnEcrypt, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(29, 29, 29)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel5)
                                                                .addGap(158, 158, 158))
                                                        .addComponent(txtDeryptMessage)
                                                        .addComponent(btnDecrypt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(ckFunction)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblSelect)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(logout)))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ckFunction)
                                        .addComponent(lblSelect)
                                        .addComponent(logout))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnEcrypt)
                                        .addComponent(btnDecrypt))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtEcryptMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtDeryptMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(13, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void ckFunctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckFunctionActionPerformed
		String select = ckFunction.isSelected() ? "( Use function)" : "( Use procedure)";
		lblSelect.setText(select);
        }//GEN-LAST:event_ckFunctionActionPerformed

        private void btnEcryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEcryptActionPerformed
		CaesarPKG ca = new CaesarPKG(conn);
		String result = "";
		String message = txtMessage.getText();
		int key = Integer.parseInt(spnKey.getValue().toString());
		result = ckFunction.isSelected() ? ca.caeserEncrypt_Func(message, key) : ca.caeserEncrypt_Proc(message, key);
		txtEcryptMessage.setText(result);
        }//GEN-LAST:event_btnEcryptActionPerformed

        private void btnDecryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecryptActionPerformed
		CaesarPKG ca = new CaesarPKG(conn);
		String result = "";
		String message = txtMessage.getText();
		int key = Integer.parseInt(spnKey.getValue().toString());
		result = ckFunction.isSelected() ? ca.caeserDecrypt_Func(message, key) : ca.caeserDecrypt_Proc(message, key);
		txtDeryptMessage.setText(result);
        }//GEN-LAST:event_btnDecryptActionPerformed

        private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
		try {
			conn = DB.logout();
			JOptionPane.showMessageDialog(null, "Logout success");
		} catch (Exception e) {
			System.err.println("error");
		}
        }//GEN-LAST:event_logoutActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(CaesarORCL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(CaesarORCL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(CaesarORCL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(CaesarORCL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new CaesarORCL().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnDecrypt;
        private javax.swing.JButton btnEcrypt;
        private javax.swing.JCheckBox ckFunction;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel lblSelect;
        private javax.swing.JButton logout;
        private javax.swing.JSpinner spnKey;
        private javax.swing.JTextArea txtDeryptMessage;
        private javax.swing.JTextArea txtEcryptMessage;
        private javax.swing.JTextArea txtMessage;
        // End of variables declaration//GEN-END:variables
}
